name: Bump Dep
on:
  push:
    branches-ignore:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print a Secret (Example)
        run: echo "The secret is $TEST_SECRET"
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
